[package]
name = "coolumn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
lazy_static = "1.4.0"
regex = "1.10.4"
termsize = "0.1.6"
